CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY, name text NOT NULL, email text UNIQUE NOT NULL, password text NOT NULL, role text NOT NULL CHECK(role IN ('AUTHOR','MODERATOR','REVIEWER','ADMIN')));
CREATE TABLE IF NOT EXISTS sessions(token text PRIMARY KEY, user_id uuid REFERENCES users(id), csrf text NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS policies(id uuid PRIMARY KEY, version int UNIQUE NOT NULL, title text NOT NULL, clauses jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS app_state(id int PRIMARY KEY CHECK(id=1), policy_id uuid REFERENCES policies(id), heartbeat timestamptz);
INSERT INTO app_state(id) VALUES(1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS drafts(id uuid PRIMARY KEY,title text NOT NULL,clauses jsonb NOT NULL,revision int NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS contents(id uuid PRIMARY KEY,author_id uuid NOT NULL REFERENCES users(id),type text NOT NULL CHECK(type IN ('POST','COMMENT')),parent_id uuid REFERENCES contents(id),visibility text NOT NULL DEFAULT 'VISIBLE' CHECK(visibility IN ('VISIBLE','REMOVED')),revision int NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS content_versions(id uuid PRIMARY KEY,content_id uuid NOT NULL REFERENCES contents(id),number int NOT NULL,text text NOT NULL,parent_text text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(content_id,number));
CREATE TABLE IF NOT EXISTS cases(id uuid PRIMARY KEY,content_id uuid NOT NULL REFERENCES contents(id),version_id uuid NOT NULL REFERENCES content_versions(id),policy_id uuid NOT NULL REFERENCES policies(id),status text NOT NULL DEFAULT 'PENDING_ANALYSIS',assignee uuid REFERENCES users(id),revision int NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reports(id uuid PRIMARY KEY,case_id uuid NOT NULL REFERENCES cases(id),reporter_id uuid NOT NULL REFERENCES users(id),version_id uuid NOT NULL REFERENCES content_versions(id),reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(case_id,reporter_id));
CREATE TABLE IF NOT EXISTS decisions(id uuid PRIMARY KEY,case_id uuid UNIQUE NOT NULL REFERENCES cases(id),actor_id uuid NOT NULL REFERENCES users(id),action text NOT NULL CHECK(action IN ('ALLOW','WARN','REMOVE')),rationale text NOT NULL,clause_keys jsonb NOT NULL,policy_id uuid NOT NULL REFERENCES policies(id),version_id uuid NOT NULL REFERENCES content_versions(id),disposition text NOT NULL,manual boolean NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS appeals(id uuid PRIMARY KEY,decision_id uuid UNIQUE NOT NULL REFERENCES decisions(id),reason text NOT NULL,evidence text NOT NULL,status text NOT NULL DEFAULT 'SUBMITTED',revision int NOT NULL DEFAULT 1,assignee uuid REFERENCES users(id),policy_id uuid NOT NULL REFERENCES policies(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS resolutions(id uuid PRIMARY KEY,appeal_id uuid UNIQUE NOT NULL REFERENCES appeals(id),actor_id uuid NOT NULL REFERENCES users(id),outcome text NOT NULL,action text NOT NULL,rationale text NOT NULL,policy_id uuid NOT NULL REFERENCES policies(id),manual boolean NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS analyses(id uuid PRIMARY KEY,case_id uuid REFERENCES cases(id),appeal_id uuid REFERENCES appeals(id),version_id uuid NOT NULL REFERENCES content_versions(id),policy_id uuid NOT NULL REFERENCES policies(id),output jsonb NOT NULL,mode text NOT NULL,model text NOT NULL,prompt_version text NOT NULL DEFAULT '1',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS jobs(id uuid PRIMARY KEY,case_id uuid REFERENCES cases(id),appeal_id uuid REFERENCES appeals(id),version_id uuid NOT NULL REFERENCES content_versions(id),policy_id uuid NOT NULL REFERENCES policies(id),status text NOT NULL DEFAULT 'QUEUED',attempts int NOT NULL DEFAULT 0,lease_token uuid,lease_until timestamptz,error text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_credentials(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id),provider text NOT NULL,model text NOT NULL,base_url text,ciphertext text NOT NULL,nonce text NOT NULL,key_suffix text NOT NULL,status text NOT NULL DEFAULT 'VERIFIED',verified_at timestamptz,version int NOT NULL DEFAULT 1,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),revoked_at timestamptz);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES users(id);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS credential_id uuid REFERENCES ai_credentials(id);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS credential_version int;
CREATE TABLE IF NOT EXISTS audit(id uuid PRIMARY KEY,actor_id uuid REFERENCES users(id),action text NOT NULL,resource_id text NOT NULL,detail jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS idempotency(scope text PRIMARY KEY,hash text NOT NULL,response jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS rate_limits(key text PRIMARY KEY,count int NOT NULL,expires_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS cases_status_idx ON cases(status,created_at,id);
CREATE INDEX IF NOT EXISTS jobs_queue_idx ON jobs(status,created_at);
CREATE INDEX IF NOT EXISTS analyses_case_idx ON analyses(case_id,created_at);
CREATE INDEX IF NOT EXISTS analyses_appeal_idx ON analyses(appeal_id,created_at);
CREATE INDEX IF NOT EXISTS content_owner_idx ON contents(author_id);
CREATE INDEX IF NOT EXISTS audit_time_idx ON audit(created_at,id);
CREATE INDEX IF NOT EXISTS ai_credentials_user_idx ON ai_credentials(user_id,active);

ALTER TABLE jobs ADD COLUMN IF NOT EXISTS requested_model text;
UPDATE jobs j SET requested_model=c.model FROM ai_credentials c WHERE j.credential_id=c.id AND j.requested_model IS NULL;
ALTER TABLE resolutions ADD COLUMN IF NOT EXISTS visibility_applied boolean NOT NULL DEFAULT true;
